name: Test github secrets with postgres and github actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: get the secrets to env file
        run: |
          echo "POSTGRES_USER=${{secrets.DB_USER}}" >> .env
          echo "POSTGRES_PASSWORD=${{secrets.DB_PASSWORD}}" >> .env

      - name: Show the env file
        run: cat .env

      - name: Set up Docker container for PostgreSQL
        run: |
          docker pull postgres:17-alpine
          docker run -d \
            --name test-postgres \
            -e POSTGRES_USER=${{secrets.DB_USER || 'postgres'}} \
            -e POSTGRES_PASSWORD=${{secrets.DB_PASSWORD || '123456'}} \
            -v ${{ github.workspace }}/init.sql:/docker-entrypoint-initdb.d/init.sql:ro \
            -p 5432:5432 \
            postgres:17-alpine

      - name: Wait for PostgreSQL to be ready
        run: |
          # Wait for PostgreSQL to be ready
          for i in {1..10}; do
            if docker exec test-postgres pg_isready -U postgres > /dev/null 2>&1; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL to be ready... ($i/30)"
            sleep 2
          done

      - name: Database logs
        if: always()
        run: docker logs test-postgres

      - name: Database container inspection
        if: always()
        run: docker inspect test-postgres
